# Generated by Django 3.2.13 on 2022-06-13 03:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220605_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sdate',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base.item')),
            ],
        ),
    ]
