# Generated by Django 3.2.13 on 2022-06-14 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220613_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
